TFL-240 Add 'Your feedback' page
UKHomeOffice/hff pull request #4
Opened 2024-07-30 09:07 UTC by jamiecarterHO

## What?

Relates
[TLF-240](https://collaboration.homeoffice.gov.uk/jira/browse/TLF-240)
[TLF-243](https://collaboration.homeoffice.gov.uk/jira/browse/TLF-243)

Adds the 'Your feedback' (`/feedback`)page to HFF along with:
- The `/feedback-sent` page view and translations.
- a behaviour to bring query information into the session on GET
- a behaviour to prepare and send a Notify request from form and session data on POST
- a util function to turn a form radio value into ordinary sentence format
- tests

## Why?

The `/feedback` page is where users will select a radio for satisfaction level from a list, and have the opportunity to add prose format 'improvements' advice. 

HFF should collect some values from the forwarding form. This can be added in the query when linked from other forms e.g. https://hof-feedback.homeoffice.gov.uk/feedback?form=ASC&returnUrl=https://google.com. Query params `form` and `returnUrl` will be consumed by the app and used in the feedback email template.

Behaviours added as they occur on the GET or POST cycle of this form step.

`/feedback-sent` page added as it is quick work and the form needs somewhere to go after success of this page.

## Testing?

Unit tests added for behaviours and utility. Tested locally (screengrabs added to ticket).
There is no remote deployment at this stage to test in any other environment

## Screenshots (optional)

<img width="1318" alt="Screenshot 2024-07-23 at 15 33 10" src="https://github.com/user-attachments/assets/11427b83-7a1a-4929-8d25-b93332649dd1">

<img width="1437" alt="hff with service name and link" src="https://github.com/user-attachments/assets/7faab18a-cb80-4b88-85aa-d90b26a62a5d">

## Check list

- [x] I have reviewed my own pull request for linting issues (e.g. adding new lines)
- [x] I have written tests (if relevant)
- [x] I have created a JIRA number for my branch
- [x] I have created a JIRA number for my commit
- [ ] Ensure drone builds are green especially tests
- [x] I will squash the commits before merging

2024-08-01 14:07 UTC, dk4g requested changes

2024-08-01 14:07 UTC, dk4g commented on README.md
> +```
as discussed, the `config.js` file is the preferred place to define the `feedbackUrl'. So this section can be removed to avoid confusion

2024-08-01 14:21 UTC, dk4g commented on apps/hff/behaviours/submit-feedback.js
> +      satisfaction = prettyPrintSentence(satisfaction);
why not to use labels from translations?

```
const translation = require('../translations/src/en/fields.json');

const getLabel = (fieldKey, fieldValue) => {
  return translation[fieldKey].options[fieldValue].label;
};

```

2024-08-02 11:43 UTC, jamiecarterHO commented on apps/hff/behaviours/submit-feedback.js
> +      logger.error('Failed to send feedback email:', error);
Interestingly I think Winston logger will extract error.message from the error object and append it to the string message, but I like your method, so will update

2024-08-02 11:52 UTC, jamiecarterHO commented on apps/hff/translations/src/en/pages.json
> +    "link-text": "Return to the GOV.UK homepage"
I see where you're coming from, but I would rather not call some text that isn't going to be on a button from e.g. `buttons.link-text`

2024-08-02 12:10 UTC, jamiecarterHO commented on utils/index.js
> +  }
Sure I think in this case readability trumps any potential efficiency save

2024-08-06 13:47 UTC, dk4g approved these changes

2024-08-06 13:51 UTC, merged